model = "F5TTS_Base"
ref_audio = "reference/reference.wav"
ref_text = "Y por eso mismo es que su trabajo, apego a los valores y constancia diarias, les hacen destacar entre sus companieros. Porque as sabemos que estamos en la misma orbita"
gen_text = "probando un dos tres fin de prueba"
remove_silence = false
output_dir = "output"
output_file = "generated_speech.wav"
